completed balance api integration
bitcoingreen/bitg-webwallet pull request #20
Opened 2018-12-04 20:07 UTC by kdbusiness121

balance api integration is completed

2018-12-04 21:31 UTC, gedanziger commented
@kdbusiness121 Check this URL: https://www.coinexplorer.net/BITG/address/GTsqojGaG2sy4uUTwyqwjxDtaVaF9ja5DV balance 20 BITG.

App is showing 0 for me on chrome desktop.

2018-12-04 21:32 UTC, gedanziger requested changes
BITG balance isn't lined up for the test address https://www.coinexplorer.net/BITG/address/GTsqojGaG2sy4uUTwyqwjxDtaVaF9ja5DV

2018-12-04 21:50 UTC, 0xweb3builder requested changes
restApi service is working good.
redux wallet is updated with correct balance.
but ui balance is not updated with correct wallet balance.
should fix this.

2018-12-05 04:32 UTC, 0xweb3builder approved these changes

2018-12-05 04:35 UTC, gedanziger approved these changes

2018-12-05 04:36 UTC, merged